### ISSUE TITLE
Getting errors when running your script

### ISSUE THREAD

**Issue by tinonetic** [ITronic/itr-acme-client#3]
Hi,

Thanks for the library. It's currently the closest simple thing that works without many requirements that are hard to get.

I am, however, facing some errors or issues from the logs (though it seems to complete the request)

The simplelog:

> 2018-04-01 18:10:26 [info] Loaded SCT Log Server with 0 and 0 operators.
> 2018-04-01 18:10:26 [debug] Save SCT Log Servers to cache: /tmp/etc/accounts/myaccount/sct_cache.json
> 2018-04-01 18:10:28 [debug] Can't get SCT entry from server: Google 'Rocketeer' log {
>   "error_message": "Invalid Request.",
>   "success": false
> }
> 
> 2018-04-01 18:10:28 [debug] Can't get SCT entry from server: Cloudflare 'Nimbus2018' Log Method Not Allowed
> method not allowed: GET
> 
> 2018-04-01 18:10:29 [debug] Can't get SCT entry from server: Google 'Argon2018' log Bad Request
> failed to verify add-chain contents: chain failed to verify: {[[ ...some digits here... ]]} because: x509: certificate signed by unknown authority
> 
> 2018-04-01 18:10:35 [debug] Can't get SCT entry from server: Cloudflare 'Nimbus2018' Log Method Not Allowed
> method not allowed: GET
> 
> 2018-04-01 18:10:36 [debug] Can't get SCT entry from server: Google 'Pilot' log {
>   "error_message": "Invalid Request.",
>   "success": false
> }
> 
> 2018-04-01 18:10:36 [notice] We don't have enough SCT log entries or different operators.

My error.log file has the following:

> [01-Apr-2018 18:10:26 America/New_York] PHP Notice:  Undefined index: logs in /home/myhomedirectory/public_html/cert/src/itr-acme-client.php on line 857
> [01-Apr-2018 18:10:26 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/myhomedirectory/public_html/cert/src/itr-acme-client.php on line 857
> [01-Apr-2018 18:10:26 America/New_York] PHP Notice:  Undefined index: operators in /home/myhomedirectory/public_html/cert/src/itr-acme-client.php on line 857
> [01-Apr-2018 18:10:26 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/myhomedirectory/public_html/cert/src/itr-acme-client.php on line 857

Any idea what I can do to fix this?

**Comment by HLeithner** [comment]
Yes sct is a bit problematic.
You properly doesn't need it, so disabling it is the easiest way.

$iac->disableSct = true;

**Comment by HLeithner** [comment]
I'm closing this because its solved.

**Comment by tinonetic** [comment]
Thank  you. Yes it was resolved
