### ISSUE TITLE
Cant renew cerificate

### ISSUE THREAD

**Issue by alexanderKikhaev** [ITronic/itr-acme-client#4]
Only regenerate without remain time check...

Can you please implement this? or may be I miss how to use it? (for cron using)

I have something like this, but it is the worsted temporary way

    if (file_exists($iac->certDir . '/cert.crt')) {
        $until = exec("openssl x509 -text -in ".$iac->certDir . '/cert.crt'." | grep -o 'Not After :[^,]*'");  $until = strtotime(mb_substr($until,12));
        if (time()<$until-86400*30) { echo "Not now\n"; die; }
    }

**Comment by HLeithner** [comment]
The library doesn't know anything about existing certificates.

We use similar code to the following code to do this

```php
$domains = ['domain.tld','www.domain.tld'];
// Load the old certificate
$pem = file_get_contents('cert.pem');
// Get todays date
$today = new Date();

// Load the expire date from the certificate 
$parsed = openssl_x509_parse($pem);
$expireDate = Date::createFromFormat('ymdHise', $parsed['validTo']);

// diff between today and expire dated
$diff = $today->diff($expireDate);
if ($diff === false) {
  $daysToExpire = 0;
} else {
  $daysToExpire = (int)$diff->format('%r%a');
}

// Create random expire date
$minDaysToExpire = 45; // Always renew if days are lower then this 
$maxDaysToExpire = 60; // Do not renew if expire date is higher then this
$expiresInDays   = mt_rand($minDaysToExpire, $maxDaysToExpire);

// Check if expires in days are lower then certificate expire days are
if ($daysToExpire < $expiresInDays) {
  try {
    $pem = $iac->signDomains($domains);
   } catch (\Exception $e) {
      print_r($e->getMessage());
      print_r($e->getTraceAsString());
      die();
    }
}
```

The reason we are doing random expire days is because we don't want to stress LE and our own systems.

I should add this to the examples...

**Comment by HLeithner** [comment]
Added example https://github.com/ITronic/itr-acme-client/blob/master/examples/simpleRenew.php and closing.
