### ISSUE TITLE
Can't renew certificate 

### ISSUE THREAD

**Issue by AKikhaev** [ITronic/itr-acme-client#7]
Worked perfect until now few years

Sending signed request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Method not allowed",
  "status": 405
}PHP Notice:  Undefined index: identifier in /data/nfs/project.com/server/acme/v1/src/itr-acme-client.php on line 517
PHP Notice:  Trying to access array offset on value of type null in /data/nfs/knpzken_ru/server/acme/v1/src/itr-acme-client.php on line 517
PHP Notice:  Undefined index: challenges in /data/nfs/project.com/server/acme/v1/src/itr-acme-client.php on line 521
PHP Warning:  Invalid argument supplied for foreach() in /data/nfs/project.com/server/acme/v1/src/itr-acme-client.php on line 521

**Comment by AKikhaev** [comment]
added my 
print_r($this->lastResponse['body']);
to show that

**Comment by HLeithner** [comment]
Does this also occur on the live system?

**Comment by AKikhaev** [comment]
no, only in testing. But my live certificate was suddenly revoked in the middle of that period 
and automatic process wanted to wait 2 months before update it.
So i get errors while investigate

**Comment by HLeithner** [comment]
we have seen some letsencrypt problem the last couple of weeks but nothing which wasn't solved after a second run....

Please try the live site, staging isn't always stable (at least that was my experience a year ago)

**Comment by HLeithner** [comment]
For us sometimes it happens that letsencrypt is unable fullfill the request. We see this on our side too but is normally gone on the next run. I'm closing this for now. If you have more information you can reopen the issue at anytime.
